[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "cherrydb"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
  "psycopg2-binary",
  "sqlparse",
  "click",
  "tabulate",
]

[project.scripts]
cherrydb = "cherrydb.cli:main"

[tool.setuptools]
packages = ["cherrydb"]
package-dir = { "cherrydb" = "." }
